module(
    name = "parallel_tree_hmm",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cuda", version = "0.3.0")
bazel_dep(name = "bidirectional_tree_rake_compress", version = "0.1.0")

accelerator_sdks = use_extension("//toolchains:extensions.bzl", "accelerator_sdks")
use_repo(accelerator_sdks, "cuda", "rocm_sdk")

git_override(
    module_name = "bidirectional_tree_rake_compress",
    commit = "36cfd7592a653011ac36ffd8e3d918acc59a2e05",
    remote = "https://github.com/joaospinto/bidirectional_tree_rake_compress.git",
)
