module(
    name = "parallel_tree_hmm",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cuda", version = "0.3.0")
bazel_dep(name = "bidirectional_tree_rake_compress", version = "0.1.0")

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.toolkit(
    name = "cuda",
    toolkit_path = "",
)
use_repo(cuda, "cuda")

local_path_override(
    module_name = "bidirectional_tree_rake_compress",
    path = "../bidirectional_tree_rake_compress",
)
